(4) SELECT Year(StreamDate), COUNT(*), SUM(Charge) FROM STREAM GROUP BY Year(StreamDate);

(5) SELECT Year, COUNT(*) AS N FROM MOVIE WHERE Duration >= 120 GROUP BY Year HAVING N >= 20;

(6) SELECT StaffId FROM STAFF WHERE Supervisor IS NULL  UNION  SELECT Manager FROM DEPARTMENT;

(7) SELECT DepId, DEPARTMENT.Name, Manager, STAFF.Name  FROM  DEPARTMENT JOIN STAFF ON (Manager=StaffId);

(8) SELECT Title, Name FROM (MOVIE NATURAL JOIN MOVIE_ACTOR) NATURAL JOIN ACTOR  WHERE  Title LIKE "%Superman%";

(9) SELECT Title, Duration, Year, StreamDate FROM MOVIE NATURAL JOIN STREAM  
    WHERE Duration >= 140 AND Year = YEAR(StreamDate) - 1;

(10) SELECT REGION.Name, COUNT(*) AS N 
     FROM REGION JOIN COUNTRY USING (RegionId) JOIN CUSTOMER ON (COUNTRY.Name=CUSTOMER.Country) GROUP BY REGION.Name;
    

